# -*- coding: utf-8 -*-
"""CS6301_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ba9OzK9cZJa0vxRqfC7zlKNAY9uwzE0h
"""

# Install required libraries
!pip install streamlit requests pandas scikit-learn pyngrok

# Import all required libraries
import re
import requests
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# URL Feature Extraction

!pip install python-Levenshtein
import Levenshtein

# List of trusted domains
trusted_domains = [
    'google.com', 'paypal.com', 'facebook.com', 'amazon.com', 'apple.com',
    'microsoft.com', 'netflix.com', 'instagram.com', 'twitter.com', 'linkedin.com',
    'youtube.com', 'reddit.com', 'wikipedia.org', 'github.com', 'stackoverflow.com',
    'twitter.com', 'whatsapp.com', 'tiktok.com', 'yahoo.com', 'bing.com',
    'dropbox.com', 'spotify.com', 'adobe.com', 'zoom.us', 'slack.com'
]

def extract_features(url):
    features = {}

    # contain https (1 if yes; 0 if no )
    features['has_https'] = 1 if url.startswith('https') else 0

    # @ symbol
    features['has_at_symbol'] = 1 if '@' in url else 0

    # contains ip
    features['has_ip_address'] = 1 if re.search(r'\d+\.\d+\.\d+\.\d+', url) else 0

    # contains suspicious keywords
    suspicious_words = ['login', 'verify', 'update', 'secure', 'banking', 'confirm', 'password', 'account']
    features['has_suspicious_words'] = 1 if any(word in url.lower() for word in suspicious_words) else 0

    # url length
    features['url_length'] = len(url)

    #check if the domain is trying to impersonate a trusted site
    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['is_lookalike'] = 0
    for trusted in trusted_domains:
        distance = Levenshtein.distance(domain, trusted)
        if distance <= 2 and domain != trusted:
            features['is_lookalike'] = 1
            break

    # more dots usually means more subdomains which is suspicious
    features['num_dots'] = url.count('.')

    # dashes
    features['num_dashes'] = url.count('-')

    # subdomains
    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['num_subdomains'] = len(domain.split('.')) - 1

    # special chars
    features['num_special_chars'] = len(re.findall(r'[^a-zA-Z0-9]', url))

    # how many digits
    features['num_digits'] = len(re.findall(r'\d', url))

    # check if URL has a port number in it
    features['has_port'] = 1 if re.search(r':\d+', url) else 0

    # measure randomness of the URL - phishing URLs tend to have high entropy
    import math
    prob = [float(url.count(c)) / len(url) for c in set(url)]
    features['entropy'] = -sum(p * math.log(p, 2) for p in prob)

    return features

# Dataset loading

# load the dataset
df = pd.read_csv('phishing_site_urls.csv')

# take a quick look at the data
print(df.head())
print(df.shape)
print(df['Label'].value_counts())

# Data preprocessing

# extract features
X = pd.DataFrame([extract_features(url) for url in df['URL']])

# convert labels to binary (1 = bad, 0 = good)
y = df['Label'].apply(lambda x: 1 if x == 'bad' else 0)

print("features shape:", X.shape)
print("label distribution:", y.value_counts())

# Model training
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# split into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# train the random forest model
model = RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

# test the model and print results
y_pred = model.predict(X_test)
print("accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Prediction Function
def predict_url(url):
    domain = re.sub(r'https?://', '', url).split('/')[0]
    if domain in trusted_domains or 'www.' + domain in trusted_domains or domain.replace('www.', '') in trusted_domains:
        return {
            'url': url,
            'result': 'safe',
            'confidence': 100.0
        }

    # extract features
    features = extract_features(url)
    features_df = pd.DataFrame([features])

    # prediction and probability from the model
    prediction = model.predict(features_df)[0]
    probability = model.predict_proba(features_df)[0]

    # convert
    if prediction == 0:
        if probability[0] >= 0.60:
            result = "safe"
        else:
            result = "suspicious"
    else:
        if probability[1] >= 0.85:
            result = "dangerous"
        else:
            result = "suspicious"

    return {
        'url': url,
        'result': result,
        'confidence': round(max(probability) * 100, 2)
    }

# test a fake vs real PayPal URL
print(predict_url("http://paypa1.com/login/verify-account"))
print(predict_url("https://www.paypal.com"))

## Blacklist Filtering
import requests


def fetch_malicious_domains():
    url = "https://raw.githubusercontent.com/amitambekar510/Malicious-Domain-Threat-List/main/Blacklisted_Malicious_Domain_Repo.txt"
    response = requests.get(url)

    if response.status_code == 200:
        return response.text.splitlines()
    else:
        raise Exception("Failed to fetch malicious domain list")


def filter_urls_against_blacklist(urls, malicious_domains):
    filtered_urls = []

    for url in urls:
        domain = url.split("//")[-1].split("/")[0]

        if domain in malicious_domains:
            filtered_urls.append((url, "malicious"))
        else:
            filtered_urls.append((url, "non-malicious"))

    return filtered_urls


def test_url_blacklist(urls):
    malicious_domains = fetch_malicious_domains()
    filtered_urls = filter_urls_against_blacklist(urls, malicious_domains)
    print("Filtered URLs:", filtered_urls)

test_url_blacklist(["https://google.com", "youtube.com", "www.kkinstagram.com", "zombicafe.com"])

# Google Safe Browsing API Integration

import os
from getpass import getpass
from urllib.parse import urlparse, urlunparse

GOOGLE_API_URL = (
    "https://safebrowsing.googleapis.com/v4/threatMatches:find"
)


# Ask for the API key if it is not already saved.
if not os.getenv("GOOGLE_SAFE_BROWSING_API_KEY"):
    api_key = getpass("Enter Google API key: ").strip()

    if api_key:
        os.environ["GOOGLE_SAFE_BROWSING_API_KEY"] = api_key


def normalize_url(url):
    # Remove spaces before and after the URL.
    url = url.strip()

    # Add https:// if the user did not enter it.
    if not re.match(r"^https?://", url, re.IGNORECASE):
        url = "https://" + url

    parsed = urlparse(url)

    # Accept only HTTP or HTTPS URLs with a domain.
    if parsed.scheme.lower() not in ["http", "https"]:
        raise ValueError("Only HTTP or HTTPS URLs are allowed.")

    if not parsed.netloc:
        raise ValueError("The URL does not contain a valid domain.")

    # Rebuild the URL without the fragment section.
    return urlunparse(
        (
            parsed.scheme.lower(),
            parsed.netloc,
            parsed.path or "/",
            parsed.params,
            parsed.query,
            "",
        )
    )


def google_error(status, message):
    return {
        "status": status,
        "message": message,
        "is_threat": False,
        "threat_types": [],
    }


def check_google_safe_browsing(url):
    api_key = os.getenv("GOOGLE_SAFE_BROWSING_API_KEY", "").strip()

    if not api_key:
        return google_error(
            "missing_key",
            "API Key is missing"
        )

    try:
        clean_url = normalize_url(url)
    except ValueError as error:
        return google_error(
            "invalid_url",
            str(error),
        )

    request_body = {
        "client": {
            "clientId": "cs6301-url-detector",
            "clientVersion": "1.0",
        },
        "threatInfo": {
            "threatTypes": [
                "MALWARE",
                "SOCIAL_ENGINEERING",
                "UNWANTED_SOFTWARE",
                "POTENTIALLY_HARMFUL_APPLICATION",
            ],
            "platformTypes": ["ANY_PLATFORM"],
            "threatEntryTypes": ["URL"],
            "threatEntries": [
                {"url": clean_url}
            ],
        },
    }

    try:
        response = requests.post(
            GOOGLE_API_URL,
            params={"key": api_key},
            json=request_body,
            timeout=10,
        )

        if response.status_code in [400, 401, 403]:
            return google_error(
                "authentication_error",
                "Check the API key and Settings",
            )

        if response.status_code == 429:
            return google_error(
                "quota_exceeded",
                "The google API quita was exceeded",
            )

        response.raise_for_status()

        data = response.json()
        threats = data.get("matches", [])

        threat_types = []

        for threat in threats:
            threat_type = threat.get("threatType")

            if threat_type and threat_type not in threat_types:
                threat_types.append(threat_type)

        return {
            "status": "ok",
            "message": "Google Safe Browsing check completed.",
            "is_threat": len(threats) > 0,
            "threat_types": threat_types,
        }

    except requests.Timeout:
        return google_error(
            "timeout",
            "The Google request timed out.",
        )

    except requests.RequestException:
        return google_error(
            "request error",
            "The Google request failed.",
        )

    except ValueError:
        return google_error(
            "response error",
            "Google returned an invalid response.",
        )

# API tests

print(check_google_safe_browsing("https://google.com"))
print(check_google_safe_browsing("https://testsafebrowsing.appspot.com/s/phishing.html"))

"""# Checklist

- Hani = StreamLit
- Brandon = backlist filtering
- Anil - Dataset preprocessing/ML model training
"""

# ============================================================
# MALICIOUS URL DETECTOR — V5 History table fix
# ============================================================

# ---- Install required libraries ----
!pip install streamlit requests pandas scikit-learn pyngrok python-Levenshtein kagglehub -q

# ---- Imports ----
import re
import os
import gc
import math
import pickle
import requests
import pandas as pd
import Levenshtein
import kagglehub
from getpass import getpass
from urllib.parse import urlparse, urlunparse
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# ---- Download dataset from Kaggle ----
path = kagglehub.dataset_download("taruntiwarihp/phishing-site-urls")
print("Path to dataset files:", path)
print("Files in dataset folder:", os.listdir(path))

# ---- Feature extraction ----
trusted_domains = [
    'google.com', 'paypal.com', 'facebook.com', 'amazon.com', 'apple.com',
    'microsoft.com', 'netflix.com', 'instagram.com', 'twitter.com', 'linkedin.com',
    'youtube.com', 'reddit.com', 'wikipedia.org', 'github.com', 'stackoverflow.com',
    'whatsapp.com', 'tiktok.com', 'yahoo.com', 'bing.com',
    'dropbox.com', 'spotify.com', 'adobe.com', 'zoom.us', 'slack.com'
]

def extract_features(url):
    features = {}

    features['has_https'] = 1 if url.startswith('https') else 0
    features['has_at_symbol'] = 1 if '@' in url else 0
    features['has_ip_address'] = 1 if re.search(r'\d+\.\d+\.\d+\.\d+', url) else 0

    suspicious_words = ['login', 'verify', 'update', 'secure', 'banking', 'confirm', 'password', 'account']
    features['has_suspicious_words'] = 1 if any(word in url.lower() for word in suspicious_words) else 0

    features['url_length'] = len(url)

    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['is_lookalike'] = 0
    for trusted in trusted_domains:
        distance = Levenshtein.distance(domain, trusted)
        if distance <= 2 and domain != trusted:
            features['is_lookalike'] = 1
            break

    features['num_dots'] = url.count('.')
    features['num_dashes'] = url.count('-')

    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['num_subdomains'] = len(domain.split('.')) - 1

    features['num_special_chars'] = len(re.findall(r'[^a-zA-Z0-9]', url))
    features['num_digits'] = len(re.findall(r'\d', url))
    features['has_port'] = 1 if re.search(r':\d+', url) else 0

    if len(url) > 0:
        prob = [float(url.count(c)) / len(url) for c in set(url)]
        features['entropy'] = -sum(p * math.log(p, 2) for p in prob)
    else:
        features['entropy'] = 0

    return features

# ---- Dataset loading ----
csv_filename = [f for f in os.listdir(path) if f.endswith('.csv')][0]
csv_path = os.path.join(path, csv_filename)
print("Loading CSV from:", csv_path)

df = pd.read_csv(csv_path)
print(df.head())
print(df.shape)
print(df['Label'].value_counts())

# ---- Data preprocessing ----
X = pd.DataFrame([extract_features(url) for url in df['URL']])
y = df['Label'].apply(lambda x: 1 if x == 'bad' else 0)

print("features shape:", X.shape)
print("label distribution:", y.value_counts())

# ---- Model training ----
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, max_depth=20, random_state=42, class_weight='balanced', n_jobs=-1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# ---- Save model ----
with open('url_model.pkl', 'wb') as f:
    pickle.dump(model, f)
print("Model saved to url_model.pkl")

# ---- Free up memory now that training data is no longer needed ----
del df, X, y, X_train, X_test, y_train, y_test
gc.collect()
print("Freed training data from memory")

# ---- Prediction function (for quick in-notebook testing) ----
def get_domain(url):
    domain = re.sub(r'https?://', '', url).split('/')[0].lower()
    domain = re.sub(r'^www\.', '', domain)
    return domain

def predict_url(url):
    features = extract_features(url)
    features_df = pd.DataFrame([features])

    domain = get_domain(url)

    prediction = model.predict(features_df)[0]
    probability = model.predict_proba(features_df)[0]
    malicious_percent = round(probability[1] * 100, 2)

    if domain in trusted_domains:
        result = "safe"
        confidence = 100.0
    elif prediction == 0:
        result = "safe" if probability[0] >= 0.65 else "suspicious"
        confidence = round(max(probability) * 100, 2)
    else:
        result = "dangerous" if probability[1] >= 0.85 else "suspicious"
        confidence = round(max(probability) * 100, 2)

    return {
        'url': url,
        'result': result,
        'confidence': confidence,
        'malicious_percent': malicious_percent,
        'features': features
    }

print(predict_url("http://paypa1.com/login/verify-account"))
print(predict_url("https://google.com"))
print(predict_url("https://www.google.com"))

# ---- Google Safe Browsing API key entry ----
if not os.getenv("GOOGLE_SAFE_BROWSING_API_KEY", "").strip():
    entered_key = getpass(
        "Enter Google Safe Browsing API key (hidden, press Enter to skip): "
    ).strip()
    if entered_key:
        os.environ["GOOGLE_SAFE_BROWSING_API_KEY"] = entered_key

print("Google Safe Browsing API key setup complete.")

# ---- Write app.py ----
app_code = '''
import streamlit as st
import pickle
import re
import os
import math
import Levenshtein
import pandas as pd
import requests
from urllib.parse import urlparse, urlunparse

with open('url_model.pkl', 'rb') as f:
    model = pickle.load(f)

trusted_domains = ''' + repr(trusted_domains) + '''

def get_domain(url):
    domain = re.sub(r'https?://', '', url).split('/')[0].lower()
    domain = re.sub(r'^www\\.', '', domain)
    return domain

def extract_features(url):
    features = {}

    features['has_https'] = 1 if url.startswith('https') else 0
    features['has_at_symbol'] = 1 if '@' in url else 0
    features['has_ip_address'] = 1 if re.search(r'\\d+\\.\\d+\\.\\d+\\.\\d+', url) else 0

    suspicious_words = ['login', 'verify', 'update', 'secure', 'banking', 'confirm', 'password', 'account']
    features['has_suspicious_words'] = 1 if any(word in url.lower() for word in suspicious_words) else 0

    features['url_length'] = len(url)

    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['is_lookalike'] = 0
    for trusted in trusted_domains:
        distance = Levenshtein.distance(domain, trusted)
        if distance <= 2 and domain != trusted:
            features['is_lookalike'] = 1
            break

    features['num_dots'] = url.count('.')
    features['num_dashes'] = url.count('-')

    domain = re.sub(r'https?://', '', url).split('/')[0]
    features['num_subdomains'] = len(domain.split('.')) - 1

    features['num_special_chars'] = len(re.findall(r'[^a-zA-Z0-9]', url))
    features['num_digits'] = len(re.findall(r'\\d', url))
    features['has_port'] = 1 if re.search(r':\\d+', url) else 0

    if len(url) > 0:
        prob = [float(url.count(c)) / len(url) for c in set(url)]
        features['entropy'] = -sum(p * math.log(p, 2) for p in prob)
    else:
        features['entropy'] = 0

    return features

def predict_url(url):
    features = extract_features(url)
    features_df = pd.DataFrame([features])

    domain = get_domain(url)

    prediction = model.predict(features_df)[0]
    probability = model.predict_proba(features_df)[0]
    malicious_percent = round(probability[1] * 100, 2)

    if domain in trusted_domains:
        result = "safe"
        confidence = 100.0
    elif prediction == 0:
        result = "safe" if probability[0] >= 0.65 else "suspicious"
        confidence = round(max(probability) * 100, 2)
    else:
        result = "dangerous" if probability[1] >= 0.85 else "suspicious"
        confidence = round(max(probability) * 100, 2)

    return {
        'url': url,
        'result': result,
        'confidence': confidence,
        'malicious_percent': malicious_percent,
        'features': features
    }

@st.cache_data(ttl=3600)
def fetch_malicious_domains():
    url = "https://raw.githubusercontent.com/amitambekar510/Malicious-Domain-Threat-List/main/Blacklisted_Malicious_Domain_Repo.txt"
    response = requests.get(url, timeout=10)
    if response.status_code == 200:
        return set(response.text.splitlines())
    else:
        raise Exception("Failed to fetch malicious domain list")

def check_blacklist(url):
    try:
        malicious_domains = fetch_malicious_domains()
        domain = url.split("//")[-1].split("/")[0]
        is_blacklisted = domain in malicious_domains
        return {"status": "ok", "domain": domain, "is_blacklisted": is_blacklisted, "message": None}
    except Exception as e:
        return {"status": "error", "domain": None, "is_blacklisted": False, "message": str(e)}

GOOGLE_SAFE_BROWSING_ENDPOINT = "https://safebrowsing.googleapis.com/v4/threatMatches:find"

def normalize_url_for_google(url):
    candidate = url.strip()
    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", candidate):
        candidate = "https://" + candidate

    parsed = urlparse(candidate)
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Please enter a valid HTTP or HTTPS URL.")

    return urlunparse((parsed.scheme.lower(), parsed.netloc, parsed.path or "/",
                        parsed.params, parsed.query, ""))

def google_error(status, message):
    return {"status": status, "message": message, "is_threat": False,
            "threat_types": [], "matched_urls": [], "cache_duration": None}

def check_google_safe_browsing(url):
    api_key = os.getenv("GOOGLE_SAFE_BROWSING_API_KEY", "").strip()
    if not api_key:
        return google_error("missing_key", "Google Safe Browsing API key is missing.")

    try:
        lookup_url = normalize_url_for_google(url)
    except ValueError as error:
        return google_error("invalid_url", str(error))

    request_body = {
        "client": {
            "clientId": "streamlit-url-detector",
            "clientVersion": "1.0",
        },
        "threatInfo": {
            "threatTypes": [
                "MALWARE",
                "SOCIAL_ENGINEERING",
                "UNWANTED_SOFTWARE",
                "POTENTIALLY_HARMFUL_APPLICATION",
            ],
            "platformTypes": ["ANY_PLATFORM"],
            "threatEntryTypes": ["URL"],
            "threatEntries": [{"url": lookup_url}],
        },
    }

    try:
        response = requests.post(
            GOOGLE_SAFE_BROWSING_ENDPOINT,
            params={"key": api_key},
            json=request_body,
            headers={"Accept": "application/json"},
            timeout=10,
        )

        if response.status_code == 400:
            if "api key" in response.text.lower():
                return google_error("authentication_error", "The Google API key was rejected.")
            return google_error("invalid_request", "Google Safe Browsing rejected the request format.")
        if response.status_code in (401, 403):
            return google_error("authentication_error", "Check the API key, API restriction, and whether Safe Browsing API is enabled.")
        if response.status_code == 429:
            return google_error("quota_exceeded", "Google Safe Browsing request quota was exceeded.")

        response.raise_for_status()
        data = response.json()
        threats = data.get("matches", []) or []

        threat_types = sorted({t.get("threatType") for t in threats if t.get("threatType")})
        matched_urls = sorted({
            t.get("threat", {}).get("url", "")
            for t in threats
            if t.get("threat", {}).get("url")
        })

        return {
            "status": "ok",
            "message": "Google Safe Browsing check completed.",
            "is_threat": bool(threats),
            "threat_types": threat_types,
            "matched_urls": matched_urls,
            "cache_duration": threats[0].get("cacheDuration") if threats else None,
        }

    except requests.Timeout:
        return google_error("timeout", "Google Safe Browsing request timed out.")
    except requests.RequestException:
        return google_error("request_error", "Google Safe Browsing request failed. Check the network connection.")
    except ValueError:
        return google_error("response_error", "Google Safe Browsing returned an invalid response.")

def format_value(v):
    if float(v).is_integer():
        return int(v)
    return round(v, 2)

st.title("URL Malicious Detector")
st.write("Enter a URL below to check whether it looks safe, suspicious, or dangerous.")

st.markdown("""
    <style>
    table.harmful-table {
        width: 100%;
        border-collapse: collapse;
    }
    table.harmful-table th {
        background-color: #b91c1c;
        color: white;
        text-align: left;
        padding: 8px 12px;
        font-size: 14px;
    }
    table.harmful-table td {
        padding: 8px 12px;
        border-bottom: 1px solid #e5e5e5;
        font-size: 14px;
    }
    table.history-table {
        width: 100%;
        border-collapse: collapse;
    }
    table.history-table th {
        background-color: #1e3a8a;
        color: white;
        text-align: left;
        padding: 8px 12px;
        font-size: 14px;
    }
    table.history-table td {
        padding: 8px 12px;
        border-bottom: 1px solid #e5e5e5;
        font-size: 14px;
    }
    table.whitelist-table {
        width: 100%;
        border-collapse: collapse;
    }
    table.whitelist-table th {
        background-color: #15803d;
        color: white;
        text-align: left;
        padding: 8px 12px;
        font-size: 14px;
    }
    table.whitelist-table td {
        padding: 8px 12px;
        border-bottom: 1px solid #e5e5e5;
        font-size: 14px;
    }
    </style>
""", unsafe_allow_html=True)

if "history" not in st.session_state:
    st.session_state.history = []

if "whitelist" not in st.session_state:
    st.session_state.whitelist = set()

if "show_history" not in st.session_state:
    st.session_state.show_history = False

if "show_whitelist" not in st.session_state:
    st.session_state.show_whitelist = False

if "last_result" not in st.session_state:
    st.session_state.last_result = None

def find_in_history(url):
    for entry in st.session_state.history:
        if entry["url"] == url:
            return entry
    return None

user_url = st.text_input("Enter a URL:")

if st.button("Check URL"):
    if user_url.strip() == "":
        st.warning("Please enter a URL.")
        st.session_state.last_result = None
    else:
        clean_url = user_url.strip()
        domain = get_domain(clean_url)

        if domain in st.session_state.whitelist:
            st.session_state.last_result = {
                "url": clean_url,
                "domain": domain,
                "source": "whitelist",
                "label": "Whitelisted",
                "confidence": None,
                "label_probability": 100.0,
                "malicious_percent": 0.0,
                "features": {},
                "blacklist_result": None,
                "gsb_result": None,
            }
        else:
            cached = find_in_history(clean_url)
            if cached:
                cached_copy = dict(cached)
                cached_copy["source"] = "cache"
                st.session_state.last_result = cached_copy
            else:
                result = predict_url(clean_url)
                conf = result["confidence"]
                malicious_percent = result["malicious_percent"]

                blacklist_result = check_blacklist(clean_url)
                gsb_result = check_google_safe_browsing(clean_url)

                features = result["features"]
                triggered = {k: v for k, v in features.items() if v != 0}

                new_entry = {
                    "url": clean_url,
                    "domain": domain,
                    "source": "fresh",
                    "label": result["result"].capitalize(),
                    "confidence": conf,
                    "label_probability": conf,
                    "malicious_percent": malicious_percent,
                    "features": triggered,
                    "blacklist_result": blacklist_result,
                    "gsb_result": gsb_result,
                }

                st.session_state.history.append(new_entry)
                st.session_state.last_result = new_entry

if st.session_state.last_result:
    r = st.session_state.last_result

    if r["source"] == "cache":
        st.info(f"This URL is already in your history — showing saved results for {r['url']}")

    if r["source"] == "whitelist":
        st.info(f"'{r['domain']}' is in your whitelist — skipping malicious URL checks.")
        st.success("This link is trusted and was not scanned.")
    else:
        label = r["label"]
        conf = r["confidence"]

        if label == "Safe":
            st.success(f"ML Model: Safe -- confidence: {conf}%")
        elif label == "Suspicious":
            st.warning(f"ML Model: Suspicious -- confidence: {conf}%")
        else:
            st.error(f"ML Model: Dangerous -- confidence: {conf}%")

        bl = r["blacklist_result"]
        bl_domain = bl.get("domain")
        bl_message = bl.get("message")

        if bl["status"] == "error":
            st.warning(f"Blacklist check failed: {bl_message}")
        elif bl["is_blacklisted"]:
            st.error(f"Blacklist: '{bl_domain}' is on the known malicious domain list.")
        else:
            st.success("Blacklist: Domain not found on the known malicious domain list.")

        gsb = r["gsb_result"]
        gsb_message = gsb.get("message")

        if gsb["status"] != "ok":
            st.warning(f"Google Safe Browsing check failed: {gsb_message}")
        elif gsb["is_threat"]:
            threat_list = ", ".join(gsb["threat_types"]) if gsb["threat_types"] else "unknown threat type"
            st.error(f"Google Safe Browsing: URL flagged as a threat ({threat_list}).")
        else:
            st.success("Google Safe Browsing: No known threats found.")

        st.subheader("Detected Features")
        triggered = r["features"]

        if triggered:
            display_rows = [
                (key.replace("_", " ").title(), format_value(value))
                for key, value in triggered.items()
            ]
            feature_df = pd.DataFrame(display_rows, columns=["Detected Signal", "Value"])
            html_table = feature_df.to_html(index=False, classes="harmful-table", border=0)
            st.markdown(html_table, unsafe_allow_html=True)
        else:
            st.write("No notable features were detected for this URL.")

    if r["domain"] in st.session_state.whitelist:
        st.write(f"This domain ('{r['domain']}') is already in your whitelist.")
    else:
        if st.button("Add to Whitelist", key=f"whitelist_add_{r['domain']}"):
            st.session_state.whitelist.add(r["domain"])
            st.rerun()

col1, col2 = st.columns(2)

with col1:
    if st.button("Toggle URL History"):
        st.session_state.show_history = not st.session_state.show_history

with col2:
    if st.button("Toggle Whitelist"):
        st.session_state.show_whitelist = not st.session_state.show_whitelist

if st.session_state.show_history:
    st.subheader("URL History")
    if st.session_state.history:
        table_rows = [
            {
                "URL": entry["url"],
                "Predicted Label": entry["label"],
                "Probability": f'{entry["label_probability"]}%'
            }
            for entry in st.session_state.history
        ]
        history_df = pd.DataFrame(table_rows)
        history_html = history_df.to_html(index=False, classes="history-table", border=0)
        st.markdown(history_html, unsafe_allow_html=True)
    else:
        st.write("No URLs have been checked yet.")

if st.session_state.show_whitelist:
    st.subheader("Whitelist")
    if st.session_state.whitelist:
        whitelist_df = pd.DataFrame(sorted(st.session_state.whitelist), columns=["Domain"])
        whitelist_html = whitelist_df.to_html(index=False, classes="whitelist-table", border=0)
        st.markdown(whitelist_html, unsafe_allow_html=True)
    else:
        st.write("No domains have been added to the whitelist yet.")
'''

with open('app.py', 'w') as f:
    f.write(app_code)

print("app.py written successfully")

# ---- Check for syntax errors before launching ----
import py_compile
try:
    py_compile.compile('app.py', doraise=True)
    print("✅ app.py has no syntax errors")
except py_compile.PyCompileError as e:
    print("❌ Syntax error in app.py:")
    print(e)

# ---- Launch Streamlit + Cloudflare tunnel with auto-restart watchdog ----
!pkill -f streamlit || true
!pkill -f cloudflared || true

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

import subprocess
import time

def start_streamlit():
    subprocess.Popen(
        "streamlit run app.py --server.port 8501 --server.address 0.0.0.0 "
        "--server.headless true >> /content/streamlit_logs.txt 2>&1",
        shell=True
    )

open("/content/streamlit_logs.txt", "w").close()
start_streamlit()
time.sleep(5)

!curl -s http://localhost:8501/_stcore/health || echo "Streamlit not responding yet"

subprocess.Popen(
    "./cloudflared tunnel --url http://localhost:8501 > /content/cloudflared_logs.txt 2>&1",
    shell=True
)
time.sleep(6)

print("🚀 Your public URL:")
!grep -o 'https://[a-zA-Z0-9.-]*\.trycloudflare\.com' /content/cloudflared_logs.txt | head -1

print("\nWatching Streamlit — it will auto-restart if it crashes.")
print("To stop everything: Runtime > Interrupt execution (or the ⏹ stop button on this cell).")

try:
    while True:
        time.sleep(5)
        health = subprocess.run(
            ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
             "http://localhost:8501/_stcore/health"],
            capture_output=True, text=True
        ).stdout
        if health != "200":
            print("⚠️  Streamlit not responding — restarting...")
            start_streamlit()
            time.sleep(5)
except KeyboardInterrupt:
    print("Interrupted — stopping Streamlit and tunnel...")
    !pkill -f streamlit || true
    !pkill -f cloudflared || true

# Google API Key
# (Removed before publishing to GitHub -- set GOOGLE_SAFE_BROWSING_API_KEY as an environment variable instead.)
